- name: Pull configuration from the host system
  hosts: all
  tasks:
    - name: pull files from home directory
      action: copy src={{ homedir }}/{{ item }} dest=files/home/{{ item }} 
      with_lines: find files/home -mindepth 1 | cut -d '/' -f 3-
