- name: Push configuration to the host system
  hosts: all
  tasks:
    - name: push files to home directory
      action: copy src=files/home/{{ item }} dest={{ homedir }}/{{ item }}
      with_lines: find files/home -type f | cut -d '/' -f 3-
    - name: Create vim backup dir
      file: path={{ homedir }}/.vim/backup state=directory
