- name: Push configuration to the host system
  hosts: all
  tasks:
    - name: push files to home directory
      action: template src=files/home/{{ item }} dest={{ homedir }}/{{ item }}
      with_lines: find files/home -mindepth 1 | cut -d '/' -f 3-
